library(shiny)

#Define UI for application

shinyUI(fluidPage(
  
  #Application title
  titlePanel("SRAexplorer!"),
  
  sidebarLayout(
    sidebarPanel("Contents"),
    mainPanel(
      h3("What is the SRAexplorer?", align = "left"),
      p("The SRAexplorer is an application designed to", strong("visualise and explore"), "the data uploaded to NCBI's Sequence Read Archive (SRA). 
        The SRA is a bioinformatics database that provides a public repository for next generation sequencing data, especially the 'short reads'
        generated by High-throughput sequencing. The SRA has yet to be entirely catalogued, so categorising the database would allow a clearer picture
        of the data available."),
      img(dna="dna.jpg", height=200, width=200),
      br(),
      h3("Features"),
      p("*"),
      p("*")
    )
  )
))
